<ADSWorkspace Revision="24" Version="100">
    <Workspace Name="">
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_virtual_test_bench" />
        <Library Name="ads_standard_layers" />
        <Library Name="adstechlib" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="MixerPager_lib" />
        <Dataset Name="BiasNet.ds" />
        <Dataset Name="BiasPoint.ds" />
        <Dataset Name="Compression.ds" />
        <Dataset Name="DC_curves.ds" />
        <Dataset Name="Gain_Comp_Curve.ds" />
        <Dataset Name="LaySimIdeal.ds" />
        <Dataset Name="LOdrive.ds" />
        <Dataset Name="LOdrive15.ds" />
        <Dataset Name="MixCompr.ds" />
        <Dataset Name="MMBR941MeasuredCompr.ds" />
        <Dataset Name="MMBR941MeasuredDC.ds" />
        <Dataset Name="MMBR941MeasuredSparams.ds" />
        <Dataset Name="RFIFmatch.ds" />
        <Dataset Name="RFIFmatch1.ds" />
        <Dataset Name="SimFromLayout.ds" />
        <Dataset Name="Sparams.ds" />
        <Dataset Name="SparamsIdeal.ds" />
        <Log Name="conversion_results.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="MixLayout_lay.prf" />
        <Preferences Name="MixLayout_schem.prf" />
        <Preferences Name="schematic.prf" />
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Folder Name="01_ReadMe">
            <Cell Name="MixerPager_lib:ReadMe" />
        </Folder>
        <Log Name="search_history.log" />
        <Folder Name="02_DC &amp; Bias Point">
            <Cell Name="MixerPager_lib:DC_curves" />
            <Data_Display Name="DC_curves.dds" />
            <Cell Name="MixerPager_lib:BiasNet" />
            <Cell Name="MixerPager_lib:BiasPoint" />
            <Data_Display Name="BiasPoint.dds" />
        </Folder>
        <Log Name="netlist.log" />
        <ConfigFile Name="dds.cfg" />
        <Folder Name="03_Compression &amp; IF Match">
            <Cell Name="MixerPager_lib:Compression" />
            <Data_Display Name="Compression.dds" />
            <Cell Name="MixerPager_lib:RFIFmatch1" />
            <Data_Display Name="RFIFmatch.dds" />
            <Cell Name="MixerPager_lib:MixCompr" />
            <Data_Display Name="MixCompr.dds" />
        </Folder>
        <Folder Name="04_LO Drive">
            <Cell Name="MixerPager_lib:LOdrive" />
            <Data_Display Name="LOdrive.dds" />
        </Folder>
        <Folder Name="05_Mixer Design &amp; Sim">
            <Cell Name="MixerPager_lib:MixerLayout" />
            <Cell Name="MixerPager_lib:SimFromLayout" />
            <Data_Display Name="SimFromLayout.dds" />
            <Data_Display Name="Sparams.dds" />
        </Folder>
    </Workspace>
</ADSWorkspace>
